Refazer hero
EdisonMatos/Site-Paper-Street pull request #43
Opened 2024-09-16 13:53 UTC by BiellSouza

2024-09-18 12:12 UTC, EdisonMatos requested changes
Inserir bolinhas mostrando a quantidade de imagens

2024-09-18 19:02 UTC, BiellSouza commented
Testado

2024-09-18 19:59 UTC, BiellSouza commented
Testado

2024-09-23 16:50 UTC, BiellSouza commented
Testado

2024-09-25 18:30 UTC, BiellSouza commented
Testado novamente

2024-09-25 19:58 UTC, merged